version: '3.8'
services:
  sniperphish:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    volumes:
      - spear_config:/var/www/html/spear/config/
      - spear_uploads:/var/www/html/spear/uploads/
      - spear_hf:/var/www/html/spear/sniperhost/hf_files/
      - spear_ht:/var/www/html/spear/sniperhost/ht_files/


  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: "${MYSQL_USER:-sniperphish}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-sniperphish}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-sniperphish}"
  
  # Mail hog is an email testing tool.
  # It acts as a simple smtp server and let's us test the mailing system locally.
  # To read sent emails, access the web interface (port 8025 by default)
  # To run it, use `docker compose --profile dev up -d --build`
  mailhog:
    image: 'mailhog/mailhog:latest'
    restart: unless-stopped
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    profiles:
        - dev


volumes:
  db_data:
  spear_config:
  spear_uploads:
  spear_hf:
  spear_ht:
